// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// get_m
int get_m(double rho, double prec, int mlo);
RcppExport SEXP _spExpM_get_m(SEXP rhoSEXP, SEXP precSEXP, SEXP mloSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type prec(precSEXP);
    Rcpp::traits::input_parameter< int >::type mlo(mloSEXP);
    rcpp_result_gen = Rcpp::wrap(get_m(rho, prec, mlo));
    return rcpp_result_gen;
END_RCPP
}
// SPS_v_exp_spQ
arma::mat SPS_v_exp_spQ(const arma::mat v, const arma::sp_mat Q, double prec, bool renorm, bool t2);
RcppExport SEXP _spExpM_SPS_v_exp_spQ(SEXP vSEXP, SEXP QSEXP, SEXP precSEXP, SEXP renormSEXP, SEXP t2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat >::type v(vSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat >::type Q(QSEXP);
    Rcpp::traits::input_parameter< double >::type prec(precSEXP);
    Rcpp::traits::input_parameter< bool >::type renorm(renormSEXP);
    Rcpp::traits::input_parameter< bool >::type t2(t2SEXP);
    rcpp_result_gen = Rcpp::wrap(SPS_v_exp_spQ(v, Q, prec, renorm, t2));
    return rcpp_result_gen;
END_RCPP
}
// MUSPS2_v_exp_spQ
arma::mat MUSPS2_v_exp_spQ(arma::rowvec v, arma::sp_mat Q, double prec, arma::vec ts);
RcppExport SEXP _spExpM_MUSPS2_v_exp_spQ(SEXP vSEXP, SEXP QSEXP, SEXP precSEXP, SEXP tsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::rowvec >::type v(vSEXP);
    Rcpp::traits::input_parameter< arma::sp_mat >::type Q(QSEXP);
    Rcpp::traits::input_parameter< double >::type prec(precSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type ts(tsSEXP);
    rcpp_result_gen = Rcpp::wrap(MUSPS2_v_exp_spQ(v, Q, prec, ts));
    return rcpp_result_gen;
END_RCPP
}
// MUSPS2r_v_exp_spQ
arma::mat MUSPS2r_v_exp_spQ(arma::rowvec v, arma::sp_mat Q, double prec, arma::vec ts);
RcppExport SEXP _spExpM_MUSPS2r_v_exp_spQ(SEXP vSEXP, SEXP QSEXP, SEXP precSEXP, SEXP tsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::rowvec >::type v(vSEXP);
    Rcpp::traits::input_parameter< arma::sp_mat >::type Q(QSEXP);
    Rcpp::traits::input_parameter< double >::type prec(precSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type ts(tsSEXP);
    rcpp_result_gen = Rcpp::wrap(MUSPS2r_v_exp_spQ(v, Q, prec, ts));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_spExpM_get_m", (DL_FUNC) &_spExpM_get_m, 3},
    {"_spExpM_SPS_v_exp_spQ", (DL_FUNC) &_spExpM_SPS_v_exp_spQ, 5},
    {"_spExpM_MUSPS2_v_exp_spQ", (DL_FUNC) &_spExpM_MUSPS2_v_exp_spQ, 4},
    {"_spExpM_MUSPS2r_v_exp_spQ", (DL_FUNC) &_spExpM_MUSPS2r_v_exp_spQ, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_spExpM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
