# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_m <- function(rho, prec, mlo = -1L) {
    .Call(`_spExpM_get_m`, rho, prec, mlo)
}

SPS_v_exp_spQ <- function(v, Q, prec, renorm = TRUE, t2 = TRUE) {
    .Call(`_spExpM_SPS_v_exp_spQ`, v, Q, prec, renorm, t2)
}

MUSPS2_v_exp_spQ <- function(v, Q, prec, ts) {
    .Call(`_spExpM_MUSPS2_v_exp_spQ`, v, Q, prec, ts)
}

MUSPS2r_v_exp_spQ <- function(v, Q, prec, ts) {
    .Call(`_spExpM_MUSPS2r_v_exp_spQ`, v, Q, prec, ts)
}

